export const automationsContent = {
  center: {
    eyebrow: "Motor financeiro local",
    title: "Central de automações",
    description:
      "Simule regras, recorrências e alertas no banco criptografado antes de aplicar qualquer alteração.",
    simulate: "Simular agora",
    apply: "Aplicar selecionadas",
    running: "Processando...",
    noPreview: "Execute uma simulação para visualizar alterações seguras.",
    noCandidates: "Nenhuma alteração automática é necessária neste momento.",
    saving: "Aguarde o banco concluir as alterações pendentes antes de simular.",
    readOnly: "As automações de escrita estão bloqueadas enquanto o banco estiver em modo somente leitura.",
  },
  summary: {
    rules: "Ajustes por regras",
    suggestions: "Sugestões do histórico",
    recurrences: "Recorrências prontas",
    alerts: "Alertas financeiros",
    selected: "Alterações selecionadas",
  },
  candidates: {
    title: "Prévia das alterações",
    description: "Nada será gravado até que você confirme a seleção.",
    selectAll: "Selecionar todas",
    clear: "Limpar seleção",
    rule: "Regra",
    suggestion: "Histórico",
    recurrence: "Recorrência",
    before: "Antes",
    after: "Depois",
  },
  alerts: {
    title: "Alertas locais",
    description: "Vencimentos e cobranças calculados sem enviar dados para serviços externos.",
    empty: "Nenhum alerta dentro da janela configurada.",
    markRead: "Marcar como lido",
    dismiss: "Dispensar",
  },
  history: {
    title: "Execuções reversíveis",
    description: "Cada aplicação guarda um snapshot dos módulos alterados.",
    empty: "Nenhuma automação foi aplicada.",
    undo: "Desfazer execução",
    applied: "Aplicada",
    undone: "Desfeita",
    failed: "Falhou",
  },
  preferences: {
    title: "Política de execução",
    simulationRequired: "Simulação obrigatória antes de aplicar",
    startupScanEnabled: "Simular pendências ao abrir a central",
    dueWindowDays: "Janela de alertas em dias",
    alertOverdue: "Alertar itens vencidos",
    alertUpcoming: "Alertar próximos vencimentos",
    save: "Salvar política",
  },
  recurrences: {
    eyebrow: "Lançamentos programados",
    title: "Recorrências locais",
    description:
      "Crie modelos para gerar lançamentos pendentes nas datas previstas. Cada ocorrência aparece primeiro na simulação.",
    create: "Nova recorrência",
    edit: "Editar",
    activate: "Ativar",
    pause: "Pausar",
    remove: "Excluir",
    empty: "Nenhuma recorrência cadastrada.",
    next: "Próxima geração",
    last: "Última geração",
  },
  dialog: {
    createTitle: "Criar recorrência",
    editTitle: "Editar recorrência",
    name: "Nome da automação",
    description: "Descrição do lançamento",
    category: "Categoria",
    account: "Conta",
    paymentMethod: "Forma de pagamento",
    amount: "Valor",
    type: "Tipo",
    status: "Situação gerada",
    frequency: "Frequência",
    interval: "Repetir a cada",
    nextRunAt: "Primeira ou próxima data",
    note: "Observação",
    active: "Ativar esta recorrência",
    cancel: "Cancelar",
    save: "Salvar recorrência",
    required: "Preencha nome, descrição, conta, valor e próxima data.",
  },
  feedback: {
    simulated: "Simulação atualizada com os dados persistidos.",
    applied: "Automações aplicadas com snapshot reversível.",
    undone: "Execução desfeita e documentos restaurados.",
    preferencesSaved: "Política de automações salva.",
    recurrenceCreated: "Recorrência criada.",
    recurrenceUpdated: "Recorrência atualizada.",
    recurrenceRemoved: "Recorrência removida.",
  },
} as const;
