export const integrationContent = {
  loading: "Abrindo sua base financeira local...",
  backendUnavailable: "Não foi possível abrir o banco SQLite local do FinnacialUX Desktop.",
  sessionExpired: "Sua sessão local foi encerrada. Entre novamente.",
  unexpectedError: "Não foi possível concluir a operação local.",
  authenticationError: "Não foi possível validar a conta local.",
  workspaceLoadError: "Não foi possível carregar os espaços financeiros locais.",
  inviteCopied: "O compartilhamento será conectado ao FinnacialUX Core em uma fase futura.",
  inviteCreated: "O compartilhamento será conectado ao FinnacialUX Core em uma fase futura.",
  localRecoveryToken: "Token local de recuperação",
  login: {
    submitting: "Entrando...",
    backendNote: "Aplicativo offline: os dados ficam armazenados neste computador.",
  },
  register: {
    submitting: "Criando conta local...",
  },
  recovery: {
    preparing: "Preparando...",
    resetNow: "Redefinir senha agora",
  },
  resetPassword: {
    eyebrow: "SEGURANÇA LOCAL",
    title: "Redefinir senha",
    description: "Use o token gerado neste computador.",
    token: "Token de recuperação",
    password: "Nova senha",
    confirmation: "Confirmar nova senha",
    validation: "Informe o token local e uma senha com pelo menos 8 caracteres.",
    mismatch: "As senhas não são iguais.",
    failure: "Não foi possível alterar a senha local.",
    submit: "Salvar nova senha",
    submitting: "Salvando...",
    back: "Voltar para o login",
    successTitle: "Senha atualizada",
    successDescription: "A senha local foi alterada com sucesso.",
    successAction: "Entrar com a nova senha",
  },
  invitation: {
    loading: "Carregando convite...",
    accepting: "Aceitando...",
    emailRestrictionPrefix: "O convite só pode ser aceito por",
  },
  accountMenu: {
    protectedSession: "Sessão local protegida",
    leaving: "Saindo...",
  },
  footerDatabase: "SQLite local — modo offline",
} as const;
