import type {
  AnomalySensitivity,
  IntelligenceScenario,
  ProjectionHorizonDays,
} from "@/types/financial-intelligence";

export const intelligenceContent = {
  title: "Inteligência financeira local",
  description: "Projete decisões com dados do próprio computador. Nenhuma informação financeira é enviada para serviços externos.",
  localBadge: "Processamento 100% local",
  horizons: {
    30: "30 dias",
    60: "60 dias",
    90: "90 dias",
    365: "365 dias",
  } satisfies Record<ProjectionHorizonDays, string>,
  scenarios: {
    conservative: { label: "Conservador", helper: "Reduz receitas e amplia a margem de segurança das despesas." },
    expected: { label: "Esperado", helper: "Usa compromissos atuais e medianas do histórico local." },
    optimistic: { label: "Otimista", helper: "Considera melhora moderada nas receitas e gastos variáveis." },
  } satisfies Record<IntelligenceScenario, { label: string; helper: string }>,
  sensitivity: {
    low: "Menos alertas",
    balanced: "Equilibrada",
    high: "Mais sensível",
  } satisfies Record<AnomalySensitivity, string>,
  controls: {
    horizon: "Horizonte",
    sensitivity: "Sensibilidade de gastos atípicos",
    threshold: "Limite de alerta do saldo",
    includeGoals: "Incluir aportes planejados das metas",
    savePreferences: "Salvar preferências",
    saveScenario: "Salvar cenário atual",
    scenarioName: "Nome do cenário",
    snapshot: "Registrar leitura",
  },
  simulator: {
    title: "Simulador de decisões",
    description: "Teste alterações sem criar lançamentos, contas ou compromissos reais.",
    incomeAdjustment: "Ajuste de receita (%)",
    fixedExpenseAdjustment: "Ajuste de despesas fixas (%)",
    variableExpenseAdjustment: "Ajuste de gastos variáveis (%)",
    oneTimeIncome: "Entrada única",
    oneTimeIncomeDate: "Data da entrada",
    oneTimeExpense: "Compra ou saída única",
    oneTimeExpenseDate: "Data da saída",
    monthlyCommitment: "Novo compromisso mensal",
    commitmentStart: "Início do compromisso",
    commitmentMonths: "Quantidade de meses",
    reset: "Limpar simulação",
  },
  summary: {
    startingBalance: "Saldo atual",
    endingBalance: "Saldo ao fim",
    lowestBalance: "Menor saldo",
    result: "Resultado projetado",
    confidence: "Confiança da estimativa",
    fixedRate: "Renda comprometida",
  },
  panels: {
    trajectory: "Trajetória projetada",
    trajectoryDescription: "Saldo consolidado ao fim de cada período mensal dentro do horizonte escolhido.",
    risks: "Riscos e próximos passos",
    risksDescription: "Alertas explicáveis ordenados pela gravidade calculada.",
    anomalies: "Gastos atípicos",
    anomaliesDescription: "Categorias ou assinaturas acima do padrão histórico recente.",
    actual: "Previsto versus realizado",
    actualDescription: "Comparação do mês atual com a mediana dos seis meses anteriores.",
    goals: "Previsão das metas",
    goalsDescription: "Estimativa de conclusão usando o aporte mensal cadastrado.",
    events: "Eventos que sustentam a projeção",
    eventsDescription: "Entradas e saídas conhecidas, históricas ou simuladas usadas no cálculo.",
    saved: "Cenários salvos",
    snapshots: "Leituras registradas",
  },
  empty: {
    risks: "Nenhum risco crítico foi encontrado no cenário atual.",
    anomalies: "Nenhum gasto atípico relevante foi detectado.",
    goals: "Nenhuma meta financeira foi cadastrada.",
    saved: "Nenhum cenário foi salvo ainda.",
    snapshots: "Nenhuma leitura foi registrada ainda.",
  },
  feedback: {
    preferencesSaved: "Preferências da inteligência local salvas.",
    scenarioSaved: "Cenário salvo no banco criptografado.",
    scenarioDeleted: "Cenário removido.",
    snapshotSaved: "Leitura da projeção registrada.",
  },
} as const;
